language: node_js

node_js:
    - "0.10"
    - "0.12"
    - "1"
    - "2"
    - "3"
    - "4"
    - "5"

install:
    - nvm install 4
    - npm install

script:
    - eslint .
    - nvm use $TRAVIS_NODE_VERSION
    - mocha
