language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"

os:
  - osx
  # - linux

env:
  - ENV=node

before_install:
  # OS X already has a GUI
  - if [[ "${TRAVIS_OS_NAME}" == 'linux' ]]; then export DISPLAY=:99.0; fi
  - if [[ "${TRAVIS_OS_NAME}" == 'linux' ]]; then sh -e /etc/init.d/xvfb start; fi

install:
  # nvm isn't yet supported on OSX
  - if [[ "${TRAVIS_OS_NAME}" == 'osx' ]]; then brew install nvm; fi
  - nvm install stable
  - npm update -g npm
  - npm install
  - nvm install ${TRAVIS_NODE_VERSION}

script:
  - nvm use stable
  - node make lint
  - nvm use ${TRAVIS_NODE_VERSION}
  - ./scripts/travis.sh

matrix:
  fast_finish: true
  # Browser tests
  # include:
  #   - node_js: stable
  #     env: ENV=chrome
  #     os: linux
  #     sudo: required
  #     dist: trusty
  #
  #   - node_js: stable
  #     env: ENV=firefox
  #     os: linux
  #     addons:
  #       firefox: latest
  #
  #   - node_js: stable
  #     env: ENV=firefox-beta
  #     os: linux
  #     addons:
  #       firefox: latest-beta
  #
  #   - node_js: stable
  #     env: ENV=firefox-esr
  #     os: linux
  #     addons:
  #       firefox: latest-esr
